apiVersion: v1
kind: Service
metadata:
  name: {{ include "fresh-grafana-mongodb-plugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fresh-grafana-mongodb-plugin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "fresh-grafana-mongodb-plugin.selectorLabels" . | nindent 4 }}
